### PR TITLE
Custom Widget For The Time Fields

### PR DESCRIPTION
**Pull request by ghost**
- Custom widget for the time fields added:
         - Blinking effect on focus
         - Increase/Decrease using scrolling or Up/Down arrow keys.
         - Become read-only on running state.

Signed-off-by: Ghasem Ramezani <g1999ramezani@gmail.com>

### CODE REVIEW

**Comment by ghost** [comment]
From the diffs, it seems you don't use any code beautifier with your IDE/Editor. That will help a lot in merging.  If you want to use it and you use Qt Creator:
1. Install `clang-format` package using your OS package manager.
2. Go to the options section (*Tools > Options...*).
3. Navigate to the Beautifier tab from the left list.
4. Check *Enable auto-format on file save* checkbox.
5. Select *ClangFormat* from the *Tool* list.
6. Go to the *Clang Format* tab and choose *Use predefined style* from the *Options* group box and set it to *File*.
7. You are done.

**Comment by fatemehkarimi** [comment]
thanks for submitting another merge request.
first, I had problems compiling your code. the compiler complained about this line in your code:
`setFont(QFont({ "Serif", "DejaVu" }, 24, 24, true));` 
I changed it to `setFont(QFont("Serif", 24, 24, true));`  and I was able to run it. please let me know If I have to compile it in another way.
second, your code has a problem; in the timer, when timeout happens, the user must be able to choose another time and restart the timer, but this is not possible in your merge request. I will be thankful if you fix it.

regards,

**Comment by fatemehkarimi** [comment]
About editor and code beautifier, I use VS Code for development. thanks for introducing clang-format. I will check how can I activate it for VS Code.

**Comment by ghost** [comment]
You're Welcome. 
- The issue with the `QFont` constructor was fixed.
    - The problem was because of my Qt version, I use Qt 6.2 which is still on testing and has a lot of crap.
- And the logical issue with the fields which remain read-only on the timer time-out was fixed.
    - The problem was because I thought I could use `TimerController::isStartCommand` to distinguish between running and stopping mode.

---------------
And about the beautifier, I choose `clang-format` for this repository because:
1. It's [LLVM kid](https://clang.llvm.org/docs/ClangFormat.html).
2. It's easy to config and use ([available options](https://clang.llvm.org/docs/ClangFormatStyleOptions.html))
3. It could be easily integrated with most Editors and IDE's.

There are still other options if you want to check:
| Name | Link |
| :---: | :---: |
| `astyle` | http://astyle.sourceforge.net |
| `uncrustify` |  http://uncrustify.sourceforge.net |

**Pull request merged**
